### ISSUE TITLE
IOS crash if apple wallet not instaled

### ISSUE THREAD

**Issue by frannale** [dev-family/react-native-wallet-manager#9]
Hi! In old devices like iphone 7 you can remove apple wallet from device. In this case the aplication crashes when you try to add a pass to the wallet.
 I try to use Linking.canOpenUrl('shoebox://') to know if device can open it, but if apple wallet is not installed this link opens directly the app store to download it...
Anyone knows some way to handle that case??

**Comment by brantleyenglish** [comment]
I ran into this same issue. I am not associated with this package, but I created a PR to hopefully workaround this:
https://github.com/dev-family/react-native-wallet-manager/pull/12

**Comment by frannale** [comment]
Interesting solution, i patch the library to resolve it too. My solution was add a new validation for this case:
<img width="662" alt="Screenshot 2023-09-15 at 17 30 39" src="https://github.com/dev-family/react-native-wallet-manager/assets/28931796/303226de-804c-4b6d-881f-dde04b1100d5">
definitely your solution is better ajja

**Comment by mshekspirtt** [comment]
Fixed in version 0.0.4.
https://github.com/dev-family/react-native-wallet-manager/blob/main/CHANGELOG.md

**Comment by ghorbani-m** [comment]
> https://github.com/dev-family/react-native-wallet-manager/blob/main/CHANGELOG.md

It is not fixed, I faced the same issue when calling `showAddPassControllerFromFile` method on IOS

**Comment by ghorbani-m** [comment]
> @ghorbani-m hi! the canAddPasses method was added. Have you used it?

Hi @mshekspirtt 
Yes, I used `canAddPasses` And it did not work, and still the App crashed, then I created a fork and made a change in IOS `walletManager` and the issue was resolved, It also seems IOS managed this situation and displayed an Alert and notifies the the user that Apple wallet is not installed

<img width="464" alt="image" src="https://github.com/user-attachments/assets/cfe71211-1313-484d-b9b7-2d409e33c00d">


This is the change log, later will create a PR
https://github.com/dev-family/react-native-wallet-manager/compare/main...ghorbani-m:react-native-wallet-manager:main

**Comment by mshekspirtt** [comment]
@ghorbani-m thank you, I look forward to your PR :)

**Comment by mshekspirtt** [comment]
fixed in version 1.1.1
thanks @ghorbani-m
